name: Generate JSDoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jsdoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20.11.1'
          cache: 'npm'

      - name: Install dependencies
        run: 
          cd jsdoc
          npm install

      - name: Install JSDoc
        run: 
          cd jsdoc
          npm install jsdoc

      - name: Generate JSDoc
        run: 
          cd jsdoc
          npx jsdoc -c jsdoc.json -r ./src -d ./docs
