name: JSDoc Generation

on:
  push:
    branches:
      - main  # O la rama en la que quieras que se ejecute

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.11.1"  # Asegúrate de que la versión esté entre comillas

      - name: Install dependencies
        run: 
          cd jsdoc
          npm install

      - name: Generate JSDoc
        run: 
          cd jsdoc
          npm run docs
