name: Generate JSDoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"

      - name: moverse a carpeta
        run: cd jsdoc

      - name: Install dependencies
        run: npm install

      - name: Generate JSDoc
        run: npm run docs


      - name: Generate JSDoc
        run: npm run docs
