name: Generate JSDoc

on:
  push:
    branches:
      - main  # O la rama que desees
  pull_request:
    branches:
      - main  # O la rama que desees

jobs:
  jsdoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20.11.1'
          cache: 'npm'  # Esto puede ayudar a acelerar las instalaciones

      - name: Install dependencies
        run: npm install
        working-directory: jsdoc  # Cambia al directorio jsdoc

      - name: Generate JSDoc
        run: npm run docs
        working-directory: jsdoc  # Asegúrate de que este sea el directorio correcto
