name: Terraform AWS Deployment

on:
  push:   #evento a hacer en este caso cuando hagamos un push
    branches:   #en la rama main
      - main

jobs:
  despliegue:   #nombre del job
    runs-on: ubuntu-latest   #maquina virtual en la que lo vamos a lanzar

    steps:   #pasos
      #este paso copia lo que hay en la rama main en la maquina virtual de ubuntu (lo de arriba)
      - name: Checkout   #nombre del action
        uses: actions/checkout@v4  #en el apartado de la derecha buscar el nombre del anterior aprametro y ponerle el uso (copiar y pegar)
      
      - name: Configurar credenciales aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"  # Cambia a la región de AWS que estás usando
          
      #este paso es para instalar terraform en la maquina virtual
      - name: INSTALAR TERRAFORM EN LA MÁQUINA VIRTUAL
        uses: 

      - name: INICIALIZAR TERRAFORM
        run: 
       

      - name: Plan Terraform
        run: 

      - name: Apply Terraform
        run: 
